import canonicalLaneMathlib.AdmissibleClass
import EvolutionaryBiologyNaturalSelectionTheoryCanonicalLaneLean.PopulationDynamics
import EvolutionaryBiologyNaturalSelectionTheoryCanonicalLaneLean.EvolutionaryGameTheory
import EvolutionaryBiologyNaturalSelectionTheoryCanonicalLaneLean.EpidemiologyModels
import EvolutionaryBiologyNaturalSelectionTheoryCanonicalLaneLean.SystemsBiology

namespace HautevilleHouse
namespace EvolutionaryBiologyNaturalSelectionTheoryCanonicalLaneLean

def ConstrainedNaturalSelectionClosure (A : AdmissibleClass) : Prop :=
  bridgeClosed A ∧ gateClosed A

theorem constrained_natural_selection_endgame (A : AdmissibleClass) :
    ConstrainedNaturalSelectionClosure A := by
  exact And.intro (bridge_from_admissible_class A) (gate_from_admissible_class A)

end EvolutionaryBiologyNaturalSelectionTheoryCanonicalLaneLean
end HautevilleHouse